### ISSUE TITLE
Client support

### ISSUE THREAD

**Issue by janoist1** [Molorius/esp32-websocket#1]
Hi,
Are you still working on the client code?
Thanks

**Comment by Molorius** [comment]
I do not have plans in the near future to implement client support, but the framework is there to do so.

**Comment by janoist1** [comment]
I see. How would you start doing it? Could you give me some idea about it? Thanks

**Comment by Molorius** [comment]
Client support is added to ESP-IDF, and given their level of support I don't see a need to implement it here. 
https://docs.espressif.com/projects/esp-idf/en/v4.1/api-reference/protocols/esp_websocket_client.html
