### ISSUE TITLE
client never gets disconnected

### ISSUE THREAD

**Issue by karelv** [Molorius/esp32-websocket#14]
I made a little python script to listen to this demo.

```py
from websocket import create_connection

uri = "ws://192.168.4.1:80"

ws = create_connection(uri) # , sslopt={"cert_reqs": ssl.CERT_NONE}
ws.timeout = 5

while True:
  msg = ws.recv()
  print (msg)
```

This little client can:
- can connect to the websocket server and in the terminal I see that it is connected.
- the client sees the message send every second by the websocket server.
- I use CTRL+c to terminate it, I know not the cleanest way, however any program can crash, right?!
     - with the original git clone I got a 'panic' reboot
     - I implemented this patch: https://github.com/Molorius/esp32-websocket/pull/7/commits/cb6a531681d5530c3b95b0d3f7234399da673c4c
     - now it does not reboot
     - the ESP does not see that the client is stopped.

See here the monitor log from 3 cycles of that python program.
```txt
I (204917) server_task: new client
I (204917) http_server: reading from client...
I (204917) http_server: read from client
I (204917) http_server: Requesting websocket on /
I (204927) websocket_callback: client 1 connected!
I (224087) server_task: new client
I (224087) http_server: reading from client...
I (224097) http_server: read from client
I (224097) http_server: Requesting websocket on /
I (224097) websocket_callback: client 2 connected!
```

Note: the disconnect with the webpage works nicely!
Note2: when I remove the `while True:` loop, and just read once, the ESP does not recognize the client disconnect neither.

**Comment by Molorius** [comment]
I moved this issue as it had more to do with the websocket component than the example code the issue was filed under. The example code this references can be found [here](https://github.com/Molorius/ESP32-Examples).

------------------------------------------------------------------------------------

I am not sure how best to deal with this issue. The line which fixed your problem was changed to solve issue #6, where the program crashes when the esp32 server and a client suddenly lose their internet connection. I will brainstorm ideas, thanks for including a demo application.

**Comment by karelv** [comment]
Hello @Molorius, 

So it turned out to be related with the example, since it uses an older branch of the websocket.
I updated the component/websocket directory, and now I got this: 

```txt
I (30525) websocket_callback: client 0 connected!
I (116845) websocket_callback: client 0 was disconnected due to an error
I (172205) server_task: new client
I (172205) http_server: reading from client...
I (172205) http_server: read from client
I (172205) http_server: Requesting websocket on /
I (172215) websocket_callback: client 0 connected!
I (194635) websocket_callback: client 0 was disconnected due to an error
I (200265) server_task: new client
I (200265) http_server: reading from client...
I (200265) http_server: read from client
I (200275) http_server: Requesting websocket on /
I (200275) websocket_callback: client 0 connected!
```

Perfectly inline with my expectations!

My suggestion would be to update the branch of the submodule in the example project:
https://github.com/Molorius/ESP32-Examples/tree/master/websocket_server/components
