### ISSUE TITLE
Update with an example which uses esp_http_server [FREQ]

### ISSUE THREAD

**Issue by freedaun** [Molorius/esp32-websocket#15]
I'm looking to use this component, but it must work with, and use, the official esp_http_server.h interface. Given I'm not yet a specialist in this stuff, progress is slow, so I'd much appreciate an example using it, or some pointers on what to implement. 

If you make an example, the websocket interface exposes a simple rx callback (to be implemented by the app) and a tx function, so an  example could provide exactly that, and leave all the internals, including the http_server, as a black box. That way the example covers >80% of all use cases out of the box. 

PS there are a few alternative github (example) repo's, which create confusion. I understand this is the main one, so I posted here.

**Comment by Molorius** [comment]
This uses lwIP for the low-level networking, not the higher-level http server provided by Espressif. I don't currently have plans to incorporate that software into this project, and would probably be better suited for a completely separate project. 

You can set up an lwip server similar to the example, but on a different port than 80, that only handles the websocket connection and upgrade. So you have the Espressif server on one port and the lwip/websocket server on a different port.

**Comment by freedaun** [comment]
The lower level works for me, so I guess I'm just misinformed and confused about how the different parts interconnect :/  

"Your example does have a http_serve(), you know", so it must be a http webserver ;)

I tried to integrate the example project into the working lwip-based sockets stack I already had (with an android app connecting), it seemed a good match, but I get no client connections. I think you'll recognize the code below. It is called right after esp_wifi_set_config(WIFI_IF_AP, &ap_config). 

That socket communication (the closing part in particular) never was quite as predictable as it could be.  

Thanks for the clarifying reply. 

    void ws_server_task()
    {
        struct netconn *conn, *connection;
        static err_t err;
        wifi.ap_clients = queue_create(AP_CLIENTS_HI, sizeof(struct netconn*));
        conn = netconn_new(NETCONN_TCP);
        netconn_bind(conn,NULL,80);
        netconn_listen(conn);
        do {
            err = netconn_accept(conn, &connection);
            // <======== never get here, I do see connection events
            if (err == ERR_OK)
            {
                xQueueSendToBack(wifi.ap_clients, &connection, portMAX_DELAY);
            }
        } while (err == ERR_OK);
        netconn_close(conn);
        netconn_delete(conn);
    }

**Comment by Molorius** [comment]
I think I misunderstood your original question. I thought by "the official esp_http_server.h interface" you meant the [HTTP Server](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/protocols/esp_http_server.html) that's part of esp-idf. 

I guess I don't understand what your question is. In the above example you are listening on port 80, then waiting for any new clients. The [netconn_accept](https://doc.ecoscentric.com/ref/lwip-api-sequential-netconn-accept.html) function is blocking until something tries to start a tcp connection on this port. That is the start of just about every lwip server, it is not specific to this websocket project. 

Edit: You should check if it is correctly bound to the port. Check the return values of netconn_bind and netconn_listen.

**Comment by freedaun** [comment]
No, you understood perfectly. 

Thanks for your kind suggestion, I will verify this tomorrow. Thanks in advance, from Brazil.
