### ISSUE TITLE
C++ implementation

### ISSUE THREAD

**Issue by gustavosinbandera1** [Molorius/esp32-websocket#20]
Good morning Molorius, my name is Gustavo Grisales , I was seeing in your awesome webscoket library, and really works pretty fine, I was doing some changes to have the library working with C++, in this moment I am working in a open source project relate with mesh wireless network, based on ESP32 and GPLv3 licence,  the link to the project is this https://github.com/btcven/turpial-firmware,
really I appreciate if you agree and let us use your library in this great project with awesome websocket library , I can put all the credits for this library in the project, thanks in advance

**Comment by Molorius** [comment]
You don't need my permission as long as you're following the terms of the license. Email me if you have more questions, as this conversion probably shouldn't occur in the issues section.

**Comment by gustavosinbandera1** [comment]
thanks , now I dont need the library, there are better approach
