### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by n1ywb** [Molorius/esp32-websocket#5]
Can you please release this code under an open source license so that we can legally use it?

**Comment by itay-grudev** [comment]
@Molorius could you publish your code under an Open Source License please?

**Comment by Molorius** [comment]
It is now under the GNU GPLv3 license.

**Comment by n1ywb** [comment]
Could you please release it under LGPL or MIT so we can actually use it? Releasing it under GPL is going to turn away most users.
